# Generated by Django 5.0.6 on 2024-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='white', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='gas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='media/cars/'),
        ),
    ]
